### ISSUE TITLE
Only 5 GA properties are listed

### ISSUE THREAD

**Issue by tguillemaud** [fileformat/heatmaptv#1]
Only the first 5 GA properties are listed

Wished: List all GA properties

**Comment by tguillemaud** [comment]
Created a PR https://github.com/fileformat/heatmaptv/pull/2

**Comment by fileformat** [comment]
PR merged, thanks!

Note: this is actually a limit of GA accounts, not properties, but there was no reason to limit it to 5 other than that's how many I tested with...
