### ISSUE TITLE
A Firebase app linked to GA blocks properties from being loaded

### ISSUE THREAD

**Issue by tguillemaud** [fileformat/heatmaptv#3]
When having a Firebase app linked to a Google Analytics property, the loader keeps spinning and no property gets loaded.
 
https://firebase.google.com/docs/analytics/

**Comment by fileformat** [comment]
I don't have a Firebase app, so I can't see exactly what is going on.  I did add a few null checks that ought to help.  Let me know if you see the related error messages.

If this doesn't fix it, can you either report what messages appear in the browser console, or give me read-only access to one of your Firebase apps?
Thanks!

**Comment by tguillemaud** [comment]
Hi @fileformat 

It appears to work now! Thanks.
